const express = require('express')
const router = express.Router()
const transactionsController = require('../../controllers/transaction-controller')

router.get('/public/currentUser', transactionsController.getCurrentUserPublicTransaction)
router.post('/:id/public', transactionsController.postPublic)
router.delete('/:id/public', transactionsController.deletePublic)
router.post('/:id/replies', transactionsController.postReply)
router.delete('/:id/deleteReplies', transactionsController.deleteReply)
router.get('/:id/replies', transactionsController.getReplies)
router.post('/:id/like', transactionsController.addLike)
router.delete('/:id/unlike', transactionsController.removeLike)
router.post('/range', transactionsController.getTransactions)
router.get('/public', transactionsController.getPublicTransactions)
router.get('/:id', transactionsController.getTransaction)
router.put('/:id', transactionsController.putTransaction)
router.delete('/:id', transactionsController.removeTransaction)
router.post('/', transactionsController.postTransaction)

module.exports = router
