DROP TABLE IF EXISTS replies;

CREATE TABLE replies (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id),
  transactoins_id INT REFERENCES transactoins(id),
  content TEXT NOT NULL,
  created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)