CREATE TABLE IF NOT EXISTS closures (
  closure_id SERIAL PRIMARY KEY,
  transaction_id INT REFERENCES transactions(id),
  quantity INT NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  closed_on TIMESTAMP NOT NULL,
  created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
